// <auto-generated />
namespace TendaAdvisors.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedadvisorColumntoadvisorNameandaddedsurnamecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedadvisorColumntoadvisorNameandaddedsurnamecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201702011513000_Changed advisorColumn to advisor Name and added surname column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
